webtalk_init -webtalk_dir C:/Users/geoge/Desktop/PROYECTO/p5/p5/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/t_p5_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 15 21:59:18 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e5bb6e2-a6bf-4b88-8bfa-7906481420f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d8c90097ad7442d9b932127981b9703" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7440_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3146711672 -regid "" -xml C:/Users/geoge/Desktop/PROYECTO/p5/p5/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/t_p5_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/geoge/Desktop/PROYECTO/p5/p5/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/t_p5_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/geoge/Desktop/PROYECTO/p5/p5/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/t_p5_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
